force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <description>Preferred restaurants</description>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Days_Since_Last_Visit__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Visit__c</fullName>
    <formula>TODAY() - Last_Visited_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Visit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Disliked_By__c.field-meta.xml
<CustomField>
    <fullName>Disliked_By__c</fullName>
    <label>Disliked By</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>People</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Last_Visited_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Visited_Date__c</fullName>
    <label>Last Visited Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Liked_By__c.field-meta.xml
<CustomField>
    <fullName>Liked_By__c</fullName>
    <label>Liked By</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>People</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&gt;10</fullName>
            </value>
            <value>
                <fullName>&lt;10</fullName>
            </value>
            <value>
                <fullName>15+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Revisitability__c.field-meta.xml
<CustomField>
    <fullName>Revisitability__c</fullName>
    <label>Revisitability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Whenever</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Wait_Time__c.field-meta.xml
<CustomField>
    <fullName>Wait_Time__c</fullName>
    <label>Wait Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nonexistent</fullName>
            </value>
            <value>
                <fullName>Short</fullName>
            </value>
            <value>
                <fullName>Long</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/People.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kyle Blair</fullName>
    </customValue>
    <customValue>
        <fullName>Kyle Chiu</fullName>
    </customValue>
    <customValue>
        <fullName>Spencer Grande</fullName>
    </customValue>
    <customValue>
        <fullName>Wesley Springer</fullName>
    </customValue>
    <customValue>
        <fullName>Cody Zeitler</fullName>
    </customValue>
    <customValue>
        <fullName>Timothy Cook</fullName>
        <isActive>false</isActive>
        <label>Timothy Cook</label>
    </customValue>
    <customValue>
        <fullName>Robert Kasprzyk</fullName>
        <isActive>false</isActive>
        <label>Robert Kasprzyk</label>
    </customValue>
    <masterLabel>People</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LunchPickerQueryService.cls
public with sharing class LunchPickerQueryService {

	private static final String QUERY_BASE = 'SELECT Name, Wait_Time__c, Liked_By__c, ' +
			'Disliked_By__c, Price__c, Last_Visited_Date__c, Revisitability__c, ' +
			'Days_Since_Last_Visit__c FROM Restaurant__c ';
	private static final String QUERY_DISLIKED_EXCLUDES = ' Disliked_By__c EXCLUDES(:';
	private static final String QUERY_WHERE_NAME_LIKE = ' WHERE Name LIKE :';
	private static final String QUERY_REVISITABILITY = ' (((Revisitability__c = \'Whenever\') OR ' +
			'(Revisitability__c = \'High\'AND Days_Since_Last_Visit__c >= 7) OR ' +
			'(Revisitability__c = \'Medium\'AND Days_Since_Last_Visit__c >= 10) OR ' +
			'(Revisitability__c = \'Low\'AND Days_Since_Last_Visit__c >= 14)) OR ' +
			'Days_Since_Last_Visit__c = null)';
	private static final String QUERY_NOT_CLOSED = ' Closed__c = false';
	private static final String QUERY_ORDER = ' ORDER BY Name ASC';
	private static String query = '';

	@AuraEnabled
	public static List<Restaurant__c> queryAllRestaurants() {
		query = QUERY_BASE + ' WHERE' + QUERY_NOT_CLOSED + QUERY_ORDER;
		return Database.query(query);
	}

	public static List<Restaurant__c> queryRestaurants() {
		query = QUERY_BASE + 'WHERE' + QUERY_REVISITABILITY + ' AND' + QUERY_NOT_CLOSED + QUERY_ORDER;
		return Database.query(query);
	}

	public static List<Restaurant__c> queryRestaurantsByName(String restaurantName) {
		String formattedName = restaurantName + '%';
		query = QUERY_BASE + QUERY_WHERE_NAME_LIKE + 'formattedName' + ' AND' + QUERY_NOT_CLOSED +
				QUERY_ORDER;
		return Database.query(query);
	}

	public static void queryRestaurantsByLiked(String names, LunchPickerController lpc) {
		names = lpc.diners.removeEnd(';');
		lpc.isFiltered = true;
		query = QUERY_BASE + 'WHERE' + QUERY_DISLIKED_EXCLUDES + 'names) AND' +
				QUERY_REVISITABILITY + ' AND' + QUERY_NOT_CLOSED + QUERY_ORDER;
		lpc.restaurants = Database.query(query);
	}

	public static void dynamicRestaurantQuery(String fieldApiName, String fieldValue, LunchPickerController lpc) {
		String names = lpc.diners.removeEnd(';');
		query = QUERY_BASE + 'WHERE ' + fieldApiName + '= :fieldValue AND' + QUERY_REVISITABILITY +
				' AND' + QUERY_NOT_CLOSED;
		if (String.isNotBlank(lpc.diners)) {
			query += ' AND' + QUERY_DISLIKED_EXCLUDES + 'names)';
		}
		query += QUERY_ORDER;
		lpc.restaurants = Database.query(query);
	}
}